### ISSUE TITLE
set_volume does not work

### ISSUE THREAD

**Issue by saschaeggi** [jaruba/ha-samsungtv-custom#3]
I can't set the Volume using set_volume

**Comment by jaruba** [comment]
I have a UE65MU6102 and a UE43RU7412, both work fine with setting the volume.

Did you install the component recently? Did you accept all the pop-ups for giving permission? I've talked to many that missed the permission pop-ups (there can be many of them after first install) say their issues disappeared after 24 hours or so.

Regardless, here is my complete config (marked XXX to anonymise data):

```
media_player:
  - platform: samsungtv_custom
    host: 192.168.1.242
    name: Living Room TV
    mac: XXX
    port: 8002
    source_list: '{"TV":"KEY_SOURCE+KEY_LEFT+KEY_LEFT+KEY_ENTER","Manual":"KEY_SOURCE+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_RIGHT+KEY_ENTER","Chromecast":"KEY_SOURCE+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_ENTER"}'
    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684"}'
  - platform: samsungtv_custom
    host: 192.168.1.77
    name: Bedroom TV
    mac: XXX
    port: 8002
    source_list: '{"TV":"KEY_SOURCE+KEY_DOWN+KEY_UP+KEY_LEFT+KEY_LEFT+KEY_ENTER","Manual":"KEY_SOURCE+KEY_DOWN+KEY_UP+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_ENTER","Chromecast":"KEY_SOURCE+KEY_DOWN+KEY_UP+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_RIGHT+KEY_ENTER"}'
    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684"}'
```

Living Room TV: UE65MU6102
Bedroom TV: UE43RU7412
